import { UniversalSiteType } from 'interfaces/UniversalSiteType';
import { ParkPayload } from './ParkPayload';
import { PhotoPayload } from './PhotoPayload';

export class SiteTypePayload  {
  id: string;
  park: ParkPayload;
  parkId: string;
  // siteTypeId: string;
  type: string;
  name: string;
  code: string;
  description: string;
  defaultArrivalTime: string;
  defaultDepartureTime: string;
  maxOccupantsPerSiteType: number;
  maxOccupantsPerSiteTypeType: number;
  bookable: boolean;
  bookableBySiteType: boolean;
  active: boolean;
  siteType: SiteTypePayload;
  altName: string;
  altDescription: string;
  primaryPhoto: PhotoPayload;
  primaryPhotoUrl: string;
  primaryPhotoId: string;
  rateSummary: string;
  universalSiteType: UniversalSiteType;
  maxAdults: number;
  maxChildren: number;
  maxPets: number;
  maxOccupancy: number;
  displayOrder: number;
  createdAt: string;
  updatedAt: string;
};
